In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score


iris = load_iris()

In [2]:
kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
kf

StratifiedKFold(n_splits=3, random_state=42, shuffle=True)

In [3]:
for train_index, test_index, in kf.split([1,2,3,4,5,6,7,8,9], [1,1,1,2,2,2,3,3,3]):
    print(train_index, test_index)

[1 2 3 4 7 8] [0 5 6]
[0 2 4 5 6 8] [1 3 7]
[0 1 3 5 6 7] [2 4 8]


In [4]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [5]:
scores_logistic = []
scores_svc = []
scores_random = []

for train_index, test_index in kf.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], \
                                        iris.target[train_index], iris.target[test_index]
    
    scores_logistic.append((get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test)))
    scores_svc.append((get_score(SVC(kernel='poly'), X_train, X_test, y_train, y_test)))
    scores_random.append((get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test)))

In [6]:
scores_logistic

[1.0, 0.94, 0.96]

In [7]:
scores_svc

[0.98, 0.94, 0.98]

In [8]:
scores_random

[0.98, 0.92, 0.94]

In [47]:
print("Logistic Regression:", cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target, cv=3))
print("SVC                :",cross_val_score(SVC(kernel='poly'), iris.data, iris.target, cv=3))
print("Random Forest      :",cross_val_score(RandomForestClassifier(n_estimators=1), iris.data, iris.target, cv=3))

Logistic Regression: [0.98 0.96 0.98]
SVC                : [0.98 0.94 0.98]
Random Forest      : [0.98 0.92 0.96]
