In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv("canada_per_capita_income.csv")
df.head()

year       income
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [2]:
model = linear_model.LinearRegression()
model.fit(df[['year']], df.income)

model.coef_

array([828.46507522])

In [3]:
model.intercept_

np.float64(-1632210.7578554575)

In [4]:
model.predict(pd.DataFrame([[2030]], columns=["year"]))

array([49573.34484664])

In [5]:
import joblib

joblib.dump(model, 'model_joblib')
mj = joblib.load('model_joblib')

In [6]:
mj.predict(pd.DataFrame([[1965]], columns=["year"]))

array([-4276.88504283])

In [7]:
mj.coef_

array([828.46507522])

In [8]:
mj.intercept_

np.float64(-1632210.7578554575)